import tomatoesImg from '../../../assets/prod_tomatoes.png';
import potatoImg from '../../../assets/prod_potatoes.png';
import onionImg from '../../../assets/prod_onions.png';
import greenChiliImg from '../../../assets/prod_green_beans.png';
import spinachImg from '../../../assets/prod_spinach.png';
import carrotsImg from '../../../assets/prod_carrots.png';
import cauliflowerImg from '../../../assets/prod_cauliflower.png';
import cucumbersImg from '../../../assets/prod_cucumbers.png';
import peppersImg from '../../../assets/prod_peppers.png';

export const mockOrders = [
  {
    id: 'ORD12345',
    orderNumber: '#ORD12345',
    customer: {
      name: 'Ramesh Kumar',
      phone: '9876543210',
      email: 'ramesh.kumar@email.com',
      address: '123, Green Street, Gomti Nagar, Lucknow, Uttar Pradesh - 226010',
    },
    itemsCount: 12,
    orderDate: '10 May 2024',
    orderTime: '09:15 AM',
    fullDateTime: '10 May 2024, 09:15 AM',
    amount: 1250.0,
    formattedAmount: '₹1,250.00',
    paymentMethod: 'COD',
    paymentMethodDetail: 'UPI (Google Pay)',
    paymentType: 'COD',
    paymentStatus: 'Paid',
    transactionId: 'pay_8x7Yt6hJkL2m',
    status: 'Delivered',
    deliveryDate: '10 May 2024, 06:10 PM',
    deliveryPartner: 'Ekart Logistics',
    trackingId: 'EK123456789IN',
    summary: {
      subtotal: 1180.0,
      deliveryCharge: 50.0,
      discount: -100.0,
      totalAmount: 1250.0,
    },
    timeline: [
      { step: 'Order Placed', time: '10 May, 09:15 AM', completed: true },
      { step: 'Confirmed', time: '10 May, 09:20 AM', completed: true },
      { step: 'Shipped', time: '10 May, 04:30 PM', completed: true },
      { step: 'Delivered', time: '10 May, 06:10 PM', completed: true },
    ],
    items: [
      {
        id: 'item-1',
        name: 'Fresh Tomatoes',
        weight: '1 kg • Organic',
        price: 40.0,
        formattedPrice: '₹40.00',
        quantity: 2,
        total: 80.0,
        formattedTotal: '₹80.00',
        image: tomatoesImg,
      },
      {
        id: 'item-2',
        name: 'Potato',
        weight: '2 kg • Organic',
        price: 60.0,
        formattedPrice: '₹60.00',
        quantity: 1,
        total: 60.0,
        formattedTotal: '₹60.00',
        image: potatoImg,
      },
      {
        id: 'item-3',
        name: 'Onion',
        weight: '1 kg • Organic',
        price: 30.0,
        formattedPrice: '₹30.00',
        quantity: 1,
        total: 30.0,
        formattedTotal: '₹30.00',
        image: onionImg,
      },
      {
        id: 'item-4',
        name: 'Green Chili',
        weight: '250 g • Organic',
        price: 20.0,
        formattedPrice: '₹20.00',
        quantity: 1,
        total: 20.0,
        formattedTotal: '₹20.00',
        image: greenChiliImg,
      },
      {
        id: 'item-5',
        name: 'Fresh Spinach',
        weight: '500 g • Organic',
        price: 35.0,
        formattedPrice: '₹35.00',
        quantity: 2,
        total: 70.0,
        formattedTotal: '₹70.00',
        image: spinachImg,
      },
      {
        id: 'item-6',
        name: 'Organic Carrots',
        weight: '1 kg • Organic',
        price: 50.0,
        formattedPrice: '₹50.00',
        quantity: 1,
        total: 50.0,
        formattedTotal: '₹50.00',
        image: carrotsImg,
      },
    ],
  },
  {
    id: 'ORD12344',
    orderNumber: '#ORD12344',
    customer: {
      name: 'Sunita Devi',
      phone: '8765432109',
      email: 'sunita.devi@email.com',
      address: '45, MG Road, Civil Lines, Allahabad, Uttar Pradesh - 211001',
    },
    itemsCount: 8,
    orderDate: '10 May 2024',
    orderTime: '08:40 AM',
    fullDateTime: '10 May 2024, 08:40 AM',
    amount: 850.0,
    formattedAmount: '₹850.00',
    paymentMethod: 'UPI',
    paymentMethodDetail: 'PhonePe',
    paymentType: 'UPI',
    paymentStatus: 'Paid',
    transactionId: 'pay_9y8Zt7hKkM3n',
    status: 'Pending',
    deliveryDate: 'Estimated 11 May 2024',
    deliveryPartner: 'Delhivery Logistics',
    trackingId: 'DEL987654321IN',
    summary: {
      subtotal: 800.0,
      deliveryCharge: 50.0,
      discount: 0.0,
      totalAmount: 850.0,
    },
    timeline: [
      { step: 'Order Placed', time: '10 May, 08:40 AM', completed: true },
      { step: 'Confirmed', time: '10 May, 09:00 AM', completed: true },
      { step: 'Shipped', time: 'Pending', completed: false },
      { step: 'Delivered', time: 'Pending', completed: false },
    ],
    items: [
      {
        id: 'item-1',
        name: 'Cauliflower',
        weight: '1 pc • Organic',
        price: 45.0,
        formattedPrice: '₹45.00',
        quantity: 2,
        total: 90.0,
        formattedTotal: '₹90.00',
        image: cauliflowerImg,
      },
      {
        id: 'item-2',
        name: 'Fresh Tomatoes',
        weight: '2 kg • Organic',
        price: 80.0,
        formattedPrice: '₹80.00',
        quantity: 2,
        total: 160.0,
        formattedTotal: '₹160.00',
        image: tomatoesImg,
      },
      {
        id: 'item-3',
        name: 'Cucumbers',
        weight: '1 kg • Organic',
        price: 40.0,
        formattedPrice: '₹40.00',
        quantity: 1,
        total: 40.0,
        formattedTotal: '₹40.00',
        image: cucumbersImg,
      },
    ],
  },
  {
    id: 'ORD12343',
    orderNumber: '#ORD12343',
    customer: {
      name: 'Amit Verma',
      phone: '7654321098',
      email: 'amit.verma@email.com',
      address: '78, Sector 15, Vasundhara, Ghaziabad, Uttar Pradesh - 201012',
    },
    itemsCount: 15,
    orderDate: '09 May 2024',
    orderTime: '07:20 PM',
    fullDateTime: '09 May 2024, 07:20 PM',
    amount: 1560.0,
    formattedAmount: '₹1,560.00',
    paymentMethod: 'Card',
    paymentMethodDetail: 'HDFC Credit Card',
    paymentType: 'Card',
    paymentStatus: 'Paid',
    transactionId: 'pay_7x6Yt5hJkL1m',
    status: 'Shipped',
    deliveryDate: 'Expected 10 May 2024',
    deliveryPartner: 'Bluedart Logistics',
    trackingId: 'BD765432109IN',
    summary: {
      subtotal: 1510.0,
      deliveryCharge: 50.0,
      discount: 0.0,
      totalAmount: 1560.0,
    },
    timeline: [
      { step: 'Order Placed', time: '09 May, 07:20 PM', completed: true },
      { step: 'Confirmed', time: '09 May, 07:35 PM', completed: true },
      { step: 'Shipped', time: '10 May, 08:00 AM', completed: true },
      { step: 'Delivered', time: 'Pending', completed: false },
    ],
    items: [
      {
        id: 'item-1',
        name: 'Bell Peppers Mix',
        weight: '500 g • Organic',
        price: 90.0,
        formattedPrice: '₹90.00',
        quantity: 2,
        total: 180.0,
        formattedTotal: '₹180.00',
        image: peppersImg,
      },
      {
        id: 'item-2',
        name: 'Potato',
        weight: '5 kg • Organic',
        price: 140.0,
        formattedPrice: '₹140.00',
        quantity: 1,
        total: 140.0,
        formattedTotal: '₹140.00',
        image: potatoImg,
      },
    ],
  },
  {
    id: 'ORD12342',
    orderNumber: '#ORD12342',
    customer: {
      name: 'Priya Sharma',
      phone: '6543210987',
      email: 'priya.sharma@email.com',
      address: '12, Park Street, Hazratganj, Lucknow, Uttar Pradesh - 226001',
    },
    itemsCount: 5,
    orderDate: '09 May 2024',
    orderTime: '06:10 PM',
    fullDateTime: '09 May 2024, 06:10 PM',
    amount: 620.0,
    formattedAmount: '₹620.00',
    paymentMethod: 'UPI',
    paymentMethodDetail: 'Paytm UPI',
    paymentType: 'UPI',
    paymentStatus: 'Paid',
    transactionId: 'pay_6x5Yt4hJkL0m',
    status: 'Delivered',
    deliveryDate: '10 May 2024, 02:30 PM',
    deliveryPartner: 'Shadowfax',
    trackingId: 'SF654321098IN',
    summary: {
      subtotal: 600.0,
      deliveryCharge: 40.0,
      discount: -20.0,
      totalAmount: 620.0,
    },
    timeline: [
      { step: 'Order Placed', time: '09 May, 06:10 PM', completed: true },
      { step: 'Confirmed', time: '09 May, 06:20 PM', completed: true },
      { step: 'Shipped', time: '10 May, 09:00 AM', completed: true },
      { step: 'Delivered', time: '10 May, 02:30 PM', completed: true },
    ],
    items: [
      {
        id: 'item-1',
        name: 'Fresh Tomatoes',
        weight: '2 kg • Organic',
        price: 80.0,
        formattedPrice: '₹80.00',
        quantity: 2,
        total: 160.0,
        formattedTotal: '₹160.00',
        image: tomatoesImg,
      },
    ],
  },
  {
    id: 'ORD12341',
    orderNumber: '#ORD12341',
    customer: {
      name: 'Vikram Singh',
      phone: '5432109876',
      email: 'vikram.singh@email.com',
      address: '89, Rajbagh, Kanpur, Uttar Pradesh - 208001',
    },
    itemsCount: 6,
    orderDate: '09 May 2024',
    orderTime: '04:30 PM',
    fullDateTime: '09 May 2024, 04:30 PM',
    amount: 430.0,
    formattedAmount: '₹430.00',
    paymentMethod: 'COD',
    paymentMethodDetail: 'Cash on Delivery',
    paymentType: 'COD',
    paymentStatus: 'Cancelled',
    transactionId: 'N/A',
    status: 'Cancelled',
    deliveryDate: 'Cancelled',
    deliveryPartner: 'N/A',
    trackingId: 'N/A',
    summary: {
      subtotal: 430.0,
      deliveryCharge: 40.0,
      discount: -40.0,
      totalAmount: 430.0,
    },
    timeline: [
      { step: 'Order Placed', time: '09 May, 04:30 PM', completed: true },
      { step: 'Cancelled', time: '09 May, 05:00 PM', completed: false, isCancelled: true },
    ],
    items: [
      {
        id: 'item-1',
        name: 'Onion',
        weight: '3 kg • Organic',
        price: 90.0,
        formattedPrice: '₹90.00',
        quantity: 1,
        total: 90.0,
        formattedTotal: '₹90.00',
        image: onionImg,
      },
    ],
  },
  {
    id: 'ORD12340',
    orderNumber: '#ORD12340',
    customer: {
      name: 'Neha Patel',
      phone: '4321098765',
      email: 'neha.patel@email.com',
      address: '34, Mall Road, Nainital, Uttarakhand - 263002',
    },
    itemsCount: 10,
    orderDate: '09 May 2024',
    orderTime: '03:15 PM',
    fullDateTime: '09 May 2024, 03:15 PM',
    amount: 980.0,
    formattedAmount: '₹980.00',
    paymentMethod: 'UPI',
    paymentMethodDetail: 'Google Pay',
    paymentType: 'UPI',
    paymentStatus: 'Paid',
    transactionId: 'pay_4x3Yt2hJkL9m',
    status: 'Pending',
    deliveryDate: 'Estimated 11 May 2024',
    deliveryPartner: 'Ekart Logistics',
    trackingId: 'EK987654321IN',
    summary: {
      subtotal: 930.0,
      deliveryCharge: 50.0,
      discount: 0.0,
      totalAmount: 980.0,
    },
    timeline: [
      { step: 'Order Placed', time: '09 May, 03:15 PM', completed: true },
      { step: 'Confirmed', time: '09 May, 03:30 PM', completed: true },
      { step: 'Shipped', time: 'Pending', completed: false },
      { step: 'Delivered', time: 'Pending', completed: false },
    ],
    items: [
      {
        id: 'item-1',
        name: 'Organic Carrots',
        weight: '2 kg • Organic',
        price: 100.0,
        formattedPrice: '₹100.00',
        quantity: 2,
        total: 200.0,
        formattedTotal: '₹200.00',
        image: carrotsImg,
      },
    ],
  },
];
